#159204728 Completes pagination support on all articles, articles belonging to an author and single article endpoints
andela/elven-ah pull request #19
Opened 2018-08-14 07:34 UTC by chukwuemekachm

#### What does this PR do?
- Completes pagination support on all articles, articles belonging to an author and single article endpoints
#### Description of Task to be completed?
- Write unit tests for the endpoints
- Create the appropriate controllers and methods
- Use POSTMAN to test the endpoints
#### How should this be manually tested?
- Clone the repository
- Start up the command line /Terminal
- Change to the repo directory
- Run `npm install`
- Run `npm run migrate`
- Run `npm run dev`
- Use POSTMAN to create a GET request to `/api/articles?limit=2&offset=2`
- Use POSTMAN to create a GET request to `/api/users/:username/articles?limit=2&offset=2`
- Use POSTMAN to create a GET request to `/api/articles/:slug`
#### Any background context you want to provide?
- Create a Postrgresql database before you start
#### What are the relevant pivotal tracker stories?
[#159204728](https://www.pivotaltracker.com/story/show/159204728)
#### Screenshots (if appropriate)

<img width="1440" alt="screen shot 2018-08-14 at 8 13 25 am" src="https://user-images.githubusercontent.com/33798252/44077859-de783b1a-9f9c-11e8-802b-43a8fb864a60.png">
<img width="1440" alt="screen shot 2018-08-14 at 8 14 10 am" src="https://user-images.githubusercontent.com/33798252/44077860-dea3c514-9f9c-11e8-970f-6629183b5006.png">

#### Questions:
- None

2018-08-14 10:31 UTC, yomigeek commented on server/controllers/ArticleController.js
> +          article: [`Article with slig: ${slug} not found.`],
Good work @chukwuemekachm, I think you needed to type slug not 'slig'.

2018-08-16 08:56 UTC, Oluwafayokemi approved these changes
Nice Job Chima! Well done.

2018-08-16 11:22 UTC, Veraclins requested changes
@chukwuemekachm Good job Bro. Just look into the comment I made and you are good to go.

2018-08-16 11:22 UTC, Veraclins commented on server/controllers/ArticleController.js
> +    if (userId) {
Hi, @chukwuemekachm good job here. I particularly love how you simplified the whole process with helper functions. I am only consigned about this part of the code. The logic of returning an error if there is a userId is difficult to understand. I see that you are using it to differentiate the error messages for a single article and multiple articles but maybe you can consider using another method for the error situations which will use an argument that will not be misleading.

2018-08-16 11:44 UTC, yomigeek approved these changes
@chukwuemekachm I am satisfied with the job done, just ensure to implement the changes requested above.

2018-08-16 12:01 UTC, chukwuemekachm commented on server/controllers/ArticleController.js
> +    if (userId) {
Thanks, @Veraclins, I know the logic is a bit confusing. I need the argument to assert that the request was made for a list of articles belonging to an author. If the operation fails, I then use the `userId` argument to send a personalized message to the user. But I will try to refactor that part.
Thanks.

2018-08-16 12:32 UTC, Veraclins approved these changes

2018-08-16 14:35 UTC, madeofhuman commented on server/tests/singleArticle.test.js
> +        res.body.article.tags.should.be.a('array');
Duuuuude!!! This is a very comprehensive test! 🙌🏾
However, did you need to test all the properties? Just a couple of unique properties would have achieved the same result. Nice work, though.

2018-08-16 14:35 UTC, merged