#159204713 Set up continuous integration
andela/elven-ah pull request #3
Opened 2018-07-24 18:03 UTC by Oluwafayokemi

## What does this Pr do?
Integrate TravisCI with readme badge

## Description of tasks to be completed
- Set up Travis
- install mocha
- install chai
- set up coveralls
- add the badge to read me
## How should this be manually tested
run npm test on your terminal
## What are the necessary pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2185767

2018-07-24 18:37 UTC, chukwuemekachm reviewed
Nice job. I can see the folder structure is different but your commit message does not specify that. Can you add that to the commit message body?

2018-07-25 09:33 UTC, tonymontaro requested changes
I see you also added coveralls, good job. Add the Travis and Coveralls badges (for the develop branch) to the Readme.

2018-07-25 09:55 UTC, Oluwafayokemi commented
Thank you for the feedback Chima. I will implement the change to the commit

On Tue, Jul 24, 2018 at 7:37 PM Chima Chukwuemeka <notifications@github.com>
wrote:

> *@chukwuemekachm* commented on this pull request.
>
> Nice job. I can see the folder structure is different but your commit
> message does not specify that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/andela/elven-ah/pull/3#pullrequestreview-140025549>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgEaprTssWZP0KS7zzZ7JS1OnAl4b6Boks5uJ2mHgaJpZM4VdM8w>
> .
>

2018-07-25 10:23 UTC, tonymontaro approved these changes

2018-07-25 10:23 UTC, merged