#160690389 remove username from required signup details and make it updateable
andela/elven-ah pull request #36
Opened 2018-09-22 16:14 UTC by madeofhuman

#### What does this PR do?
Removes the username property from required data for user signup, automatically create a username for the user from their first name, and make the username property updateable

#### Description of Task to be completed?
- remove username property from required data for user signup
- automatically create a username for the user from their first name
- make the username property updateable

#### How should this be manually tested?
- Clone the repository
- Use the `.env.example` to fill in the `.env` file
- Startup the command line
- Run `npm install`
- Run `npm start`
- Make a POST request to `/api/v1/auth/signup` and create an account with the properties `firstName`, `lastName`, `email`, `password`, and `confirmPassword`. The username property will be automatically generated from your first name and added to your user details on creation.
- Make a PUT request to `/api/v1/users/:username` and update your profile with the properties `firstName`, `lastName`, `email`, `username`, `password`, and `confirmPassword`. Note that your email address will cannot be changed.

#### Any background context you want to provide?
- The username field was removed from the signup process so we can reduce the amount of information the user had to supply.

#### What are the relevant pivotal tracker stories?
- [#160690389](https://www.pivotaltracker.com/story/show/160690389)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

[Delivers #160690389]

2018-09-26 14:16 UTC, yomigeek requested changes

2018-09-26 14:16 UTC, yomigeek commented on server/v1/controllers/AuthController.js
> +    const username = AuthController.createUsername(firstName, lastName);
Good work @madeofhuman , at the createUsername method you only have a single parameter but at the point of usage you passed in two arguments. Please kindly fix this.

2018-09-26 14:17 UTC, madeofhuman commented on server/v1/controllers/AuthController.js
> +    const username = AuthController.createUsername(firstName, lastName);
Thanks for pointing this out, Yomi. I will quickly fix it.

2018-09-26 15:26 UTC, yomigeek approved these changes

2018-09-26 15:36 UTC, chukwuemekachm requested changes
Well done, @madeofhuman.
I like how you created a separate method to help create a username for a new user in lieu of adding the logic to the signup user method. This makes the code neat.
However, I feel you should also create a method or mechanism to ensure that the username is always unique and belongs to a single user. This is because the username field on our User model has a unique constraint and if a user tries to update their profile with a username which already belongs to another user the operation/database will crash.
Please endeavour to resolve this.
Good job.

2018-09-26 16:19 UTC, madeofhuman commented
Thanks for pointing that out, @chukwuemekachm . I have fixed it.

2018-09-26 16:33 UTC, chukwuemekachm approved these changes
Welldone @madeofhuman.

2018-09-26 19:10 UTC, Veraclins approved these changes
@madeofhuman Good job here! @chukwuemekachm has raised the only concern I had and you have fixed that. So kudos and keep it up!

2018-09-27 09:41 UTC, tonymontaro commented
@madeofhuman change the base branch to develop

2018-09-27 09:53 UTC, madeofhuman commented
> @madeofhuman change the base branch to develop

I have done that. I had to rebase on develop first. @tonymontaro

2018-09-27 10:26 UTC, tonymontaro approved these changes
Nice work!

2018-09-27 10:27 UTC, merged