#159204715 Users should get JWT on successful registration
andela/elven-ah pull request #6
Opened 2018-07-29 17:25 UTC by Veraclins

#### What does this PR do?
Add Authentication through JWTs and a Middleware to protect auth-only routes
#### Description of Task to be completed?
- add support for signing and verifying JWTs
- add a middleware to protect auth-only routes
- add ES6 support for tests and coverage using babel-polyfill
- add mocha support to eslintrc.js (prevents Eslint from flagging describe() and it() as undefined)
- modify .travis.yml to enable tests to run on travis
#### How should this be manually tested?
- Clone the repo: Run `git clone https://github.com/andela/elven-ah.git` in the folder where you want the repo to be saved.
- Navigate into the newly created folder and install the dependencies: `cd elven-ah && npm install`
- Copy .env.example to .env: `cp .env.example .env`
- Provision a PostgreSQL database and add the credentials to the .env file. 
- Start the server using `npm start`
- Make a POST request to http://localhost:3000/api/users/testUser using postman submitting the following fields in the body of x-www-form-urlencoded or as raw JSON:
    - username
    - email
    - password
- add the field `x-access-token` (with the token received above as value) to request header
- send a GET request to http://localhost:3000/api/users
#### What are the relevant pivotal tracker stories? 
[#159204715](https://www.pivotaltracker.com/story/show/159204715)
#### Screenshots
<img width="1440" alt="screen shot 2018-07-29 at 5 16 52 pm" src="https://user-images.githubusercontent.com/26969309/43368810-d48093b2-935a-11e8-8577-700491932bb4.png">

2018-07-30 20:27 UTC, madeofhuman requested changes
You did a nice work, Clinton! I especially love how you commented your methods with jsdoc. Keep it up as it'll help other devs seamlessly onboard onto your code.

However, I just noticed that your controller naming is in the plural form which does not really follow convention (you have `UsersController.js` instead of `UserController.js`, and `ArticlesController.js` instead of `ArticleController.js`. You can push a commit that fixes that into this PR, and try as much as you can to follow the agreed-upon conventions, as they'll make our code look seamless.

2018-07-31 11:28 UTC, tonymontaro commented on .travis.yml
> +  - npm install -g nyc sequelize-cli
Any reason why 'nyc' and 'sequelize-cli' are being installed globally.

2018-07-31 16:37 UTC, madeofhuman requested changes
@Veraclins you've really done a good job so far. Well done. I've left some reviews for you to go through, please do that as soon as you can so we can move ahead without any errors.

2018-07-31 16:37 UTC, madeofhuman commented on server/controllers/ArticleController.js
>  export default class ArticlesController {
I noticed you changed the name of the file. Well done. However, your class name is still pluralised. Please review and make the necessary change as soon as you can.

2018-07-31 16:37 UTC, madeofhuman commented on server/controllers/UserController.js
I noticed you changed the name of the file. Well done. However, your class name is still pluralised. Please review and make the necessary change as soon as you can.

2018-07-31 16:37 UTC, madeofhuman commented on server/routes/users.js
> +import UsersController from '../controllers/UserController';
You also need to change your imports accordingly after renaming the class, to avoid pointing to an unexisting object.

2018-07-31 16:49 UTC, madeofhuman approved these changes

2018-07-31 17:58 UTC, tonymontaro approved these changes
Good job.

2018-07-31 17:59 UTC, merged